repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      language_version: python3
      exclude: >
        (?x)^(
          test-runner/adapters/rest/generated/ |
          docker_images/pythonv2/wrapper/swagger_server/ |
          horton_helpers/autorest_service_apis/
        )
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0  # Use the ref you want to point at
    hooks:
    - id: flake8
      args: ['--config=.flake8']
      exclude: >
        (?x)^(
          test-runner/adapters/rest/generated/ |
          docker_images/pythonv2/wrapper/swagger_server/ |
          horton_helpers/autorest_service_apis/
        )
