/*
 * Azure IOT End-to-End Test Wrapper Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// device twin or module twin
    /// </summary>
    [DataContract]
    public partial class DefinitionsJsontwin : IEquatable<DefinitionsJsontwin>
    { 
        /// <summary>
        /// desired properties
        /// </summary>
        /// <value>desired properties</value>

        [DataMember(Name="desired")]
        public Object Desired { get; set; }

        /// <summary>
        /// reported properties
        /// </summary>
        /// <value>reported properties</value>

        [DataMember(Name="reported")]
        public Object Reported { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DefinitionsJsontwin {\n");
            sb.Append("  Desired: ").Append(Desired).Append("\n");
            sb.Append("  Reported: ").Append(Reported).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DefinitionsJsontwin)obj);
        }

        /// <summary>
        /// Returns true if DefinitionsJsontwin instances are equal
        /// </summary>
        /// <param name="other">Instance of DefinitionsJsontwin to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DefinitionsJsontwin other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Desired == other.Desired ||
                    Desired != null &&
                    Desired.Equals(other.Desired)
                ) && 
                (
                    Reported == other.Reported ||
                    Reported != null &&
                    Reported.Equals(other.Reported)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Desired != null)
                    hashCode = hashCode * 59 + Desired.GetHashCode();
                    if (Reported != null)
                    hashCode = hashCode * 59 + Reported.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DefinitionsJsontwin left, DefinitionsJsontwin right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DefinitionsJsontwin left, DefinitionsJsontwin right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
