# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConnectResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, connection_id=None):  # noqa: E501
        """ConnectResponse - a model defined in Swagger

        :param connection_id: The connection_id of this ConnectResponse.  # noqa: E501
        :type connection_id: str
        """
        self.swagger_types = {
            'connection_id': str
        }

        self.attribute_map = {
            'connection_id': 'connectionId'
        }

        self._connection_id = connection_id

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The connectResponse of this ConnectResponse.  # noqa: E501
        :rtype: ConnectResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection_id(self):
        """Gets the connection_id of this ConnectResponse.

        unique identifier for this connection  # noqa: E501

        :return: The connection_id of this ConnectResponse.
        :rtype: str
        """
        return self._connection_id

    @connection_id.setter
    def connection_id(self, connection_id):
        """Sets the connection_id of this ConnectResponse.

        unique identifier for this connection  # noqa: E501

        :param connection_id: The connection_id of this ConnectResponse.
        :type connection_id: str
        """

        self._connection_id = connection_id
