# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """LogMessage - a model defined in Swagger

        :param message: The message of this LogMessage.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The logMessage of this LogMessage.  # noqa: E501
        :rtype: LogMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this LogMessage.

        text of message  # noqa: E501

        :return: The message of this LogMessage.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this LogMessage.

        text of message  # noqa: E501

        :param message: The message of this LogMessage.
        :type message: str
        """

        self._message = message
