# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Twin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, desired=None, reported=None):  # noqa: E501
        """Twin - a model defined in Swagger

        :param desired: The desired of this Twin.  # noqa: E501
        :type desired: object
        :param reported: The reported of this Twin.  # noqa: E501
        :type reported: object
        """
        self.swagger_types = {
            'desired': object,
            'reported': object
        }

        self.attribute_map = {
            'desired': 'desired',
            'reported': 'reported'
        }

        self._desired = desired
        self._reported = reported

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The twin of this Twin.  # noqa: E501
        :rtype: Twin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def desired(self):
        """Gets the desired of this Twin.

        desired properties  # noqa: E501

        :return: The desired of this Twin.
        :rtype: object
        """
        return self._desired

    @desired.setter
    def desired(self, desired):
        """Sets the desired of this Twin.

        desired properties  # noqa: E501

        :param desired: The desired of this Twin.
        :type desired: object
        """

        self._desired = desired

    @property
    def reported(self):
        """Gets the reported of this Twin.

        reported properties  # noqa: E501

        :return: The reported of this Twin.
        :rtype: object
        """
        return self._reported

    @reported.setter
    def reported(self, reported):
        """Sets the reported of this Twin.

        reported properties  # noqa: E501

        :param reported: The reported of this Twin.
        :type reported: object
        """

        self._reported = reported
