jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: csharp
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_container"
  continueOnError: true
  strategy:
    matrix:
      csharp_mqtt_edgehub_module_fi:    { suite: csharp_mqtt_edgehub_module_fi }
      csharp_mqttws_edgehub_module_fi:  { suite: csharp_mqttws_edgehub_module_fi }
      csharp_amqp_edgehub_module_fi:    { suite: csharp_amqp_edgehub_module_fi }
      csharp_amqpws_edgehub_module_fi:  { suite: csharp_amqpws_edgehub_module_fi }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

