jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      edgehub_module_mqtt_fi: { suite: edgehub_module_fi_mqtt }
      edgehub_module_mqtt_ws_fi: { suite: edgehub_module_fi_mqtt_ws }
      edgehub_module_amqp_fi: { suite: edgehub_module_fi_amqp }
      edgehub_module_amqp_ws_fi: { suite: edgehub_module_fi_amqp_ws }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

