jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    variant: py36
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    variant: py27

- job: "test_py36"
  dependsOn:
    - "build_py36_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py36:
        suite: edgehub_module_mqtt
      iothub_module_and_device_mqtt_py36:
        suite: iothub_module_and_device_mqtt
      iothub_module_and_device_mqtt_py36_async:
        suite: iothub_module_and_device_mqtt
        async: yes
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py36

- job: "test_py27"
  dependsOn:
    - "build_py27_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py27:
        suite: edgehub_module_mqtt
      iothub_module_and_device_mqtt_py27:
        suite: iothub_module_and_device_mqtt
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py27

