jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: java
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  pool:
    name: $(Horton.Pool)
    vmimage: $(Horton.VmImage)
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      java_mqtt_iothub_module:      { suite: java_mqtt_iothub_module }
      java_mqtt_edgehub_module:     { suite: java_mqtt_edgehub_module }
      java_mqttws_iothub_module:    { suite: java_mqttws_iothub_module }
      java_mqttws_edgehub_module:   { suite: java_mqttws_edgehub_module }
      java_amqp_iothub_module:      { suite: java_amqp_iothub_module }
      java_amqp_edgehub_module:     { suite: java_amqp_edgehub_module }
      java_amqpws_iothub_module:    { suite: java_amqpws_iothub_module }
      java_amqpws_edgehub_module:   { suite: java_amqpws_edgehub_module }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

