jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py37
    variant: py37
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    variant: py36
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py35
    variant: py35
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py34
    variant: py34
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    variant: py27

- job: "test_py37"
  pool: Hosted Ubuntu 1604
  dependsOn:
    - "build_py37_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py37:
        suite: edgehub_module_mqtt
      iothub_module_and_device_mqtt_py37:
        suite: iothub_module_and_device_mqtt
      edgehub_module_mqtt_py37_async:
        suite: edgehub_module_mqtt
        async: yes
      iothub_module_and_device_mqtt_py37_async:
        suite: iothub_module_and_device_mqtt
        async: yes
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py37

- job: "test_py36"
  pool: Hosted Ubuntu 1604
  dependsOn:
    - "build_py36_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py36_async:
        suite: edgehub_module_mqtt
        async: yes
      iothub_module_and_device_mqtt_py36_async:
        suite: iothub_module_and_device_mqtt
        async: yes
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py36

- job: "test_py35"
  pool: Hosted Ubuntu 1604
  dependsOn:
    - "build_py35_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py35_async:
        suite: edgehub_module_mqtt
        async: yes
      iothub_module_and_device_mqtt_py35_async:
        suite: iothub_module_and_device_mqtt
        async: yes
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py35

- job: "test_py34"
  pool: Hosted Ubuntu 1604
  dependsOn:
    - "build_py34_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py34:
        suite: edgehub_module_mqtt
      iothub_module_and_device_mqtt_py34:
        suite: iothub_module_and_device_mqtt
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py34

- job: "test_py27"
  pool: Hosted Ubuntu 1604
  dependsOn:
    - "build_py27_container"
  strategy:
    matrix:
      edgehub_module_mqtt_py27:
        suite: edgehub_module_mqtt
      iothub_module_and_device_mqtt_py27:
        suite: iothub_module_and_device_mqtt
  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      async: $(async)
      variant: py27

