parameters:
  langauge: ''
  repo: ''
  commit: ''
  forced_image: ''
  job_tag: 'linux'
  variant: ''

jobs:
- job: 'build_${{ parameters.job_tag }}_container'
  steps:

  - template: steps-ensure-e2e-fx-repo.yaml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - powershell: |
      $BuildImage="yes"
      if ($env:ForcedImage -ne "") {
        $BuildImage="no"
      }
      $NormalizedRepo=$env:Repo
      if ($NormalizedRepo -like 'https://github.com/*') {
        $NormalizedRepo=$NormalizedRepo.Substring('https://github.com/'.length)
      }

      Write-Host "##vso[task.setvariable variable=buildImage]${BuildImage}"
      Write-Host "##vso[task.setvariable variable=normalizedRepo]${NormalizedRepo}"
      Write-Host "BuildImage=${BuildImage}"
      Write-Host "normalizedRepo=${NormalizedRepo}"
    displayName: Custom task execution logic
    env:
      ForcedImage: ${{ parameters.forced_image }}
      Repo: ${{ parameters.repo }}
    ignoreLASTEXITCODE: false
    errorActionPreference: Stop
    failOnStderr: true

  - script: |
      cd ${BUILD_SOURCESDIRECTORY} &&
      tar --exclude .git/ -zcf ${AGENT_BUILDDIRECTORY}/source.tar.gz . &&
      mkdir -p $(Build.SourcesDirectory)/source_artifact/${{ parameters.job_tag }}
      cp ${AGENT_BUILDDIRECTORY}/source.tar.gz $(Build.SourcesDirectory)/source_artifacts/${{ parameters.job_tag }}/ &&
      mv ${AGENT_BUILDDIRECTORY}/source.tar.gz ${HORTON_FRAMEWORKROOT}/ci-wrappers/${{ parameters.language }}/ 
    displayName: "pack local language repo"
    condition: and(
        succeeded(), 
        eq(variables['buildImage'],'yes'),
        not(eq(variables['Horton.FrameworkRoot'], variables['Build.SourcesDirectory']))
        )

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
    condition: and(succeeded(), eq(variables['buildImage'],'yes'))

  - script: |
      python3 -m pip install -r $(Horton.FrameworkRoot)/pyscripts/requirements.txt
    displayName: "pip install requirements.txt"
    condition: and(succeeded(), eq(variables['buildImage'],'yes'))

  - script: |
      python3 $(Horton.FrameworkRoot)/pyscripts/build_docker_image.py --language ${{ parameters.language }}  --repo ${NormalizedRepo}  --commit ${{ parameters.commit }} --variant ${{ parameters.variant }}
    displayName: "build docker image ${{ parameters.language }}"
    condition: and(succeeded(), eq(variables['buildImage'],'yes'))
    env: 
      IOTHUB_E2E_REPO_ADDRESS: $(IOTHUB-E2E-REPO-ADDRESS)
      IOTHUB_E2E_REPO_USER: $(IOTHUB-E2E-REPO-USER)
      IOTHUB_E2E_REPO_PASSWORD: $(IOTHUB-E2E-REPO-PASSWORD)
      NormalizedRepo: $(NormalizedRepo)

  - task: CopyFiles@2
    displayName: 'Copy source tar to artifact staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/source_artifacts'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(
        always(), 
        eq(variables['Horton.SaveTar'], 'yes')
        )

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'sources'
    condition: and(
        always(), 
        eq(variables['Horton.SaveTar'], 'yes')
        )
