jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      hub_module_mqtt: { suite: hub_module_mqtt }
      edge_module_mqtt: { suite: edge_module_mqtt }
      hub_module_mqtt_ws: { suite: hub_module_mqtt_ws }
      edge_module_mqtt_ws: { suite: edge_module_mqtt_ws }
      hub_module_amqp: { suite: hub_module_amqp }
      hub_module_amqp_ws: { suite: hub_module_amqp_ws }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

