jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv1
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      pythonv1_mqtt_iothub_module:      { suite: pythonv1_mqtt_iothub_module }
      pythonv1_mqtt_edgehub_module:     { suite: pythonv1_mqtt_edgehub_module }
      pythonv1_mqttws_iothub_module:    { suite: pythonv1_mqttws_iothub_module }
      pythonv1_mqttws_edgehub_module:   { suite: pythonv1_mqttws_edgehub_module }
      pythonv1_amqp_iothub_module:      { suite: pythonv1_amqp_iothub_module }
      pythonv1_amqpws_iothub_module:    { suite: pythonv1_amqpws_iothub_module }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

