jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: c
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  pool:
    name: $(Horton.Pool)
    vmimage: $(Horton.VmImage)
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      c_mqtt_iothub_module:     { suite: c_mqtt_iothub_moduled }
      c_mqtt_edgehub_module:    { suite: c_mqtt_edgehub_module }
      c_mqttws_iothub_module:   { suite: c_mqttws_iothub_module }
      c_mqttws_edgehub_module:  { suite: c_mqttws_edgehub_module }
      c_amqp_iothub_module:     { suite: c_amqp_iothub_module }
      c_amqpws_iothub_module:   { suite: c_amqpws_iothub_module }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

