jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    language: node

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      node_mqtt_iothub_module:      { suite: node_mqtt_iothub_module }
      node_mqtt_edgehub_module:     { suite: node_mqtt_edgehub_module }
      node_mqttws_iothub_module:    { suite: node_mqttws_iothub_module }
      node_mqttws_edgehub_module:   { suite: node_mqttws_edgehub_module }
      node_amqp_iothub_module:      { suite: node_amqp_iothub_module }
      node_amqp_edgehub_module:     { suite: node_amqp_edgehub_module }
      node_amqpws_iothub_module:    { suite: node_amqpws_iothub_module }
      node_amqpws_edgehub_module:   { suite: node_amqpws_edgehub_module }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
