parameters:
  index: '1'

jobs:
- job: 'edgehub_mqtt_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: steps-ensure-e2e-fx-repo.yaml
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      testgroup: testgroup_edgehub_module_client
      job_name: 'edgehub_mqtt_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'edgehub_mqtt_${{ parameters.index }}'

- job: 'edgehub_mqttws_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: steps-ensure-e2e-fx-repo.yaml
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqttws
      testgroup: testgroup_edgehub_module_client
      job_name: 'edgehub_mqttws_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'edgehub_mqttws_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'pythonpreview', 'python')))

- job: 'edgehub_amqp_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: steps-ensure-e2e-fx-repo.yaml
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: amqp
      testgroup: testgroup_edgehub_module_client
      job_name: 'edgehub_amqp_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'edgehub_amqp_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'python', 'c', 'pythonpreview')))

- job: 'edgehub_amqpws_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: steps-ensure-e2e-fx-repo.yaml
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: amqpws
      testgroup: testgroup_edgehub_module_client
      job_name: 'edgehub_amqps_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'edgehub_amqpws_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'python', 'c', 'pythonpreview')))

