
jobs:
- job: "build_linux_amd64"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps-build-docker-image.yaml
    parameters:
      language: csharp

- job: "test_linux_amd64"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_amd64"
  continueOnError: true
  strategy:
    matrix:
      csharp_mqtt_edgehub_module_fi:    { suite: csharp_mqtt_edgehub_module_fi }
      csharp_mqttws_edgehub_module_fi:  { suite: csharp_mqttws_edgehub_module_fi }
      csharp_amqp_edgehub_module_fi:    { suite: csharp_amqp_edgehub_module_fi }
      csharp_amqpws_edgehub_module_fi:  { suite: csharp_amqpws_edgehub_module_fi }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

