jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      iothub_module_mqtt: { suite: iothub_module_mqtt }
      edgehub_module_mqtt: { suite: edgehub_module_mqtt }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

