parameters:
  index: '1'

jobs:
- job: 'iothub_mqtt_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      testgroup: testgroup_iothub_module_client
      extra_args: --direct-to-iothub
      job_name: 'iothub_mqtt_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'iothub_mqtt_${{ parameters.index }}'

- job: 'iothub_mqttws_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqttws
      testgroup: testgroup_iothub_module_client
      extra_args: --direct-to-iothub
      job_name: 'iothub_mqttws_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'iothub_mqttws_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'pythonpreview')))

- job: 'iothub_amqp_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: amqp
      testgroup: testgroup_iothub_module_client
      extra_args: --direct-to-iothub
      job_name: 'iothub_amqp_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'iothub_amqp_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'pythonpreview')))

- job: 'iothub_amqpws_${{ parameters.index }}'
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: pre-test-steps.yaml
    parameters:
      forced_image: $(FORCED_IMAGE)
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: pytest-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: amqpws
      testgroup: testgroup_iothub_module_client
      extra_args: --direct-to-iothub
      job_name: 'iothub_amqpws_${{ parameters.index }}'
  - template: post-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      job_name: 'iothub_amqpws_${{ parameters.index }}'
  condition: and(succeeded(),not(in(variables['TARGET_SDK'], 'pythonpreview')))


