jobs:
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py38
    variant: py38
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py37
    variant: py37
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    variant: py36
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py35
    variant: py35
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py34
    variant: py34
- template: jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    variant: py27

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_py27_container"
    - "build_py34_container"
    - "build_py35_container"
    - "build_py36_container"
    - "build_py37_container"
    - "build_py38_container"
  strategy:
    matrix:
        py38_mqtt_iothub_module_and_device:         { suite: py38_mqtt_iothub_module_and_device }
        py38_mqttws_async_edgehub_module:           { suite: py38_mqttws_async_edgehub_module }
        py37_mqtt_edgehub_module:                   { suite: py37_mqtt_edgehub_module }
        py37_mqttws_async_iothub_module_and_device: { suite: py37_mqttws_async_iothub_module_and_device }
        py36_mqtt_async_edgehub_module:             { suite: py36_mqtt_async_edgehub_module }
        py36_mqtt_async_iothub_module_and_device:   { suite: py36_mqtt_async_iothub_module_and_device }
        py35_mqtt_async_edgehub_module:             { suite: py35_mqtt_async_edgehub_module }
        py35_mqttws_async_iothub_module_and_device: { suite: py35_mqttws_async_iothub_module_and_device }
        py34_mqttws_edgehub_module:                 { suite: py34_mqttws_edgehub_module }
        py34_mqtt_iothub_module_and_device:         { suite: py34_mqtt_iothub_module_and_device }
        py27_mqtt_edgehub_module:                   { suite: py27_mqtt_edgehub_module }
        py27_mqttws_iothub_module_and_device:       { suite: py27_mqttws_iothub_module_and_device }
        py38_mqtt_iothub_module_quick_drop:         { suite: py38_mqtt_iothub_module_quick_drop }
        py37_mqtt_edgehub_module_quick_drop:        { suite: py37_mqtt_edgehub_module_quick_drop }
        py36_mqtt_iothub_device_quick_drop:         { suite: py36_mqtt_iothub_device_quick_drop }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

