jobs:
- job: "build_linux_amd64"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps-build-docker-image.yaml
    parameters:
      variant: node12

- job: "test_linux_amd64"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_amd64"
  strategy:
    matrix:
      node12_mqtt_iothub_module:      { suite: node12_mqtt_iothub_module }
      node12_mqtt_edgehub_module:     { suite: node12_mqtt_edgehub_module }
      node12_mqttws_iothub_module:    { suite: node12_mqttws_iothub_module }
      node12_mqttws_edgehub_module:   { suite: node12_mqttws_edgehub_module }
      node12_amqp_iothub_module:      { suite: node12_amqp_iothub_module }
      node12_amqp_edgehub_module:     { suite: node12_amqp_edgehub_module }
      node12_amqpws_iothub_module:    { suite: node12_amqpws_iothub_module }
      node12_amqpws_edgehub_module:   { suite: node12_amqpws_edgehub_module }

  steps:
  - template: steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
