resources:
- repo: self
variables:
  language: $(TARGET_SDK)
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
jobs:

- job: 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/steps-build-docker-image.yaml 
    parameters:
      language: $(TARGET_SDK)
      repo: $(REPO)
      branch: $(TARGET_BRANCH)
      commit: $(CHANGESET)

- job: 'edgehub_fi_mqtt'
  strategy:
      parallel: 8
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/pre-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_$(Agent.JobName)
  - template: templates/post-test-steps.yaml
    parameters:
      job_name: $(Agent.JobName)

