resources:
- repo: self
variables:
  language: $(TARGET_SDK)
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
jobs:

- job: 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/build-docker-image-steps.yaml 
    parameters:
      language: $(TARGET_SDK)
      repo: $(REPO)
      branch: $(TARGET_BRANCH)
      commit: $(CHANGESET)

- job: 'edgehub_fi_mqtt'
  timeoutInMinutes: 100
  dependsOn:
    - 'build_linux_containers'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/pre-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      imagetag: 'vsts-$(Build.BuildId)'
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_1
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_2
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_3
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_4
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_5
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_6
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_7
  - template: templates/edgehub-fi-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      transport: mqtt
      tag: edgehub_fi_8
  - template: templates/post-test-steps.yaml
    parameters:
      job_name: $(Agent.JobName)

