name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- job: "build_linux_amd64"
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
        c:      { language: c }
        java:   { language: java }
        csharp: { language: csharp }
        node6:  { variant: node6 }
        node8:  { variant: node8 }
        node10: { variant: node10 }
        py27:   { variant: py27 }
        py35:   { variant: py35 }
        py36:   { variant: py36 }
        py37:   { variant: py37 }
        py38:   { variant: py38 }


- job: "test_linux_amd64"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    "build_linux_amd64"

  strategy:
    matrix:
      c_mqtt_iothub_module:     { suite: c_mqtt_iothub_moduled }
      c_mqtt_edgehub_module:    { suite: c_mqtt_edgehub_module }
      c_mqttws_iothub_module:   { suite: c_mqttws_iothub_module }
      c_mqttws_edgehub_module:  { suite: c_mqttws_edgehub_module }
      c_amqp_iothub_module:     { suite: c_amqp_iothub_module }
      c_amqpws_iothub_module:   { suite: c_amqpws_iothub_module }

      csharp_mqtt_iothub_module:    { suite: csharp_mqtt_iothub_module }
      csharp_mqtt_edgehub_module:   { suite: csharp_mqtt_edgehub_module }
      csharp_mqttws_iothub_module:  { suite: csharp_mqttws_iothub_module }
      csharp_mqttws_edgehub_module: { suite: csharp_mqttws_edgehub_module } 
      csharp_amqp_iothub_module:    { suite: csharp_amqp_iothub_module }
      csharp_amqp_edgehub_module:   { suite: csharp_amqp_edgehub_module }
      csharp_amqpws_iothub_module:  { suite: csharp_amqpws_iothub_module }
      csharp_amqpws_edgehub_module: { suite: csharp_amqpws_edgehub_module }

      java_mqtt_iothub_module:      { suite: java_mqtt_iothub_module }
      java_mqtt_edgehub_module:     { suite: java_mqtt_edgehub_module }
      java_mqttws_iothub_module:    { suite: java_mqttws_iothub_module }
      java_mqttws_edgehub_module:   { suite: java_mqttws_edgehub_module }
      java_amqp_iothub_module:      { suite: java_amqp_iothub_module }
      java_amqp_edgehub_module:     { suite: java_amqp_edgehub_module }
      java_amqpws_iothub_module:    { suite: java_amqpws_iothub_module }
      java_amqpws_edgehub_module:   { suite: java_amqpws_edgehub_module }

      node6_mqtt_iothub_module:     { suite: node6_mqtt_iothub_module }
      node6_mqtt_edgehub_module:    { suite: node6_mqtt_edgehub_module }
      node6_mqttws_iothub_module:   { suite: node6_mqttws_iothub_module }
      node6_mqttws_edgehub_module:  { suite: node6_mqttws_edgehub_module }
      node6_amqp_iothub_module:     { suite: node6_amqp_iothub_module }
      node6_amqp_edgehub_module:    { suite: node6_amqp_edgehub_module }
      node6_amqpws_iothub_module:   { suite: node6_amqpws_iothub_module }
      node6_amqpws_edgehub_module:  { suite: node6_amqpws_edgehub_module }

      node8_mqtt_iothub_module:     { suite: node8_mqtt_iothub_module }
      node8_mqtt_edgehub_module:    { suite: node8_mqtt_edgehub_module }
      node8_mqttws_iothub_module:   { suite: node8_mqttws_iothub_module }
      node8_mqttws_edgehub_module:  { suite: node8_mqttws_edgehub_module }
      node8_amqp_iothub_module:     { suite: node8_amqp_iothub_module }
      node8_amqp_edgehub_module:    { suite: node8_amqp_edgehub_module }
      node8_amqpws_iothub_module:   { suite: node8_amqpws_iothub_module }
      node8_amqpws_edgehub_module:  { suite: node8_amqpws_edgehub_module }

      node10_mqtt_iothub_module:    { suite: node10_mqtt_iothub_module }
      node10_mqtt_edgehub_module:   { suite: node10_mqtt_edgehub_module }
      node10_mqttws_iothub_module:  { suite: node10_mqttws_iothub_module }
      node10_mqttws_edgehub_module: { suite: node10_mqttws_edgehub_module }
      node10_amqp_iothub_module:    { suite: node10_amqp_iothub_module }
      node10_amqp_edgehub_module:   { suite: node10_amqp_edgehub_module }
      node10_amqpws_iothub_module:  { suite: node10_amqpws_iothub_module }
      node10_amqpws_edgehub_module: { suite: node10_amqpws_edgehub_module }

      py27_mqtt_iothub_module_and_device:           { suite: py27_mqtt_iothub_module_and_device }
      py27_mqtt_edgehub_module:                     { suite: py27_mqtt_edgehub_module }
      py27_mqttws_iothub_module_and_device:         { suite: py27_mqttws_iothub_module_and_device }
      py27_mqttws_edgehub_module:                   { suite: py27_mqttws_edgehub_module }

      py35_mqtt_iothub_module_and_device:           { suite: py35_mqtt_iothub_module_and_device }
      py35_mqtt_edgehub_module:                     { suite: py35_mqtt_edgehub_module }
      py35_mqttws_iothub_module_and_device:         { suite: py35_mqttws_iothub_module_and_device }
      py35_mqttws_edgehub_module:                   { suite: py35_mqttws_edgehub_module }

      py35_mqtt_async_iothub_module_and_device:     { suite: py35_mqtt_async_iothub_module_and_device }
      py35_mqtt_async_edgehub_module:               { suite: py35_mqtt_async_edgehub_module }
      py35_mqttws_async_iothub_module_and_device:   { suite: py35_mqttws_async_iothub_module_and_device }
      py35_mqttws_async__edgehub_module:            { suite: py35_mqttws_async__edgehub_module }

      py36_mqtt_iothub_module_and_device:           { suite: py36_mqtt_iothub_module_and_device }
      py36_mqtt_edgehub_module:                     { suite: py36_mqtt_edgehub_module }
      py36_mqttws_iothub_module_and_device:         { suite: py36_mqttws_iothub_module_and_device }
      py36_mqttws_edgehub_module:                   { suite: py36_mqttws_edgehub_module }

      py36_mqtt_async_iothub_module_and_device:     { suite: py36_mqtt_async_iothub_module_and_device }
      py36_mqtt_async_edgehub_module:               { suite: py36_mqtt_async_edgehub_module }
      py36_mqttws_async_iothub_module_and_device:   { suite: py36_mqttws_async_iothub_module_and_device }
      py36_mqttws_async_edgehub_module:             { suite: py36_mqttws_async_edgehub_module }

      py37_mqtt_iothub_module_and_device:           { suite: py37_mqtt_iothub_module_and_device }
      py37_mqtt_edgehub_module:                     { suite: py37_mqtt_edgehub_module }
      py37_mqttws_iothub_module_and_device:         { suite: py37_mqttws_iothub_module_and_device }
      py37_mqttws_edgehub_module:                   { suite: py37_mqttws_edgehub_module }

      py37_mqtt_async_iothub_module_and_device:     { suite: py37_mqtt_async_iothub_module_and_device }
      py37_mqtt_async_edgehub_module:               { suite: py37_mqtt_async_edgehub_module }
      py37_mqttws_async_iothub_module_and_device:   { suite: py37_mqttws_async_iothub_module_and_device }
      py37_mqttws_async_edgehub_module:             { suite: py37_mqttws_async_edgehub_module }

      py38_mqtt_iothub_module_and_device:           { suite: py38_mqtt_iothub_module_and_device }
      py38_mqtt_edgehub_module:                     { suite: py38_mqtt_edgehub_module }
      py38_mqttws_iothub_module_and_device:         { suite: py38_mqttws_iothub_module_and_device }
      py38_mqttws_edgehub_module:                   { suite: py38_mqttws_edgehub_module }

      py38_mqtt_async_iothub_module_and_device:     { suite: py38_mqtt_async_iothub_module_and_device }
      py38_mqtt_async_edgehub_module:               { suite: py38_mqtt_async_edgehub_module }
      py38_mqttws_async_iothub_module_and_device:   { suite: py38_mqttws_async_iothub_module_and_device }
      py38_mqttws_async_edgehub_module:             { suite: py38_mqttws_async_edgehub_module }

  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)


