name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

stages:
- stage: setup
  jobs:
  - job: create_azure_resources
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: templates/steps-create-azure-resources.yaml

- stage: build_and_test
  dependsOn: setup
  jobs:
  - job: "build_linux_amd64"
    pool:
      vmImage: 'ubuntu-22.04'
    strategy:
      matrix:
          py311:  { variant: py311 }
    steps:
    - template: templates/steps-load-test-config.yaml
    - template: templates/steps-build-docker-image.yaml
      parameters:
        language: $(language)
        variant: $(variant)

  - job: "test_linux_amd64"
    pool:
        vmImage: 'ubuntu-22.04'
    dependsOn:
      - "build_linux_amd64"
    strategy:
      matrix:
        py311_friend_default_tls:
          suite: py311_mqtt_edgehub_module
          testcase: "-k friend"
          IOTHUB_E2E_EDGE_LOG_LEVEL: "debug"
          IOTHUB_E2E_EDGE_SSL_PROTOCOLS: ""
        py311_friend_tls12_only:
          suite: py311_mqtt_edgehub_module
          testcase: "-k friend"
          IOTHUB_E2E_EDGE_LOG_LEVEL: "debug"
          IOTHUB_E2E_EDGE_SSL_PROTOCOLS: "Tls12"
    steps:
    - template: templates/steps-load-test-config.yaml
    - template: templates/steps-deploy-and-run-pytest.yaml
      parameters:
        suite: $(suite)
        testcase: $(testcase)

- stage: cleanup
  dependsOn:
  - setup
  - build_and_test
  condition: always()
  jobs:
  - job: destroy_azure_resource_group
    condition: always()
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
    - template: templates/steps-destroy-azure-resources.yaml

