name: $(BuildID)_$(Horton.Language)_$(Horton.Commit)_$(BuildDefinitionName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
jobs:
- template: templates/jobs-gate-node.yaml
#- template: templates/jobs-gate-node-pwsh.yaml