name: $(BuildID)_pythonv1_$(Horton.Commit)_$(BuildDefinitionName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
  Horton.Pool: 'Azure Pipelines'
  Horton.VmImage: 'Ubuntu 16.04'
jobs:
- template: templates/jobs-gate-pythonv1.yaml
