name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

stages:
- stage: setup
  jobs:
  - job: create_azure_resources
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: templates/steps-create-azure-resources.yaml

- stage: build_and_test
  dependsOn: setup
  jobs:
  - job: "build_linux_amd64"
    pool:
      vmImage: 'ubuntu-22.04'
    strategy:
      matrix:
          node18:  { variant: node18 }
          c:      { language: c }
          java:   { language: java }
          csharp: { language: csharp }
          py312:  { variant: py312 }
    steps:
    - template: templates/steps-load-test-config.yaml
    - template: templates/steps-build-docker-image.yaml
      parameters:
        language: $(language)
        variant: $(variant)

  - job: "test_linux_amd64"
    pool:
        vmImage: 'ubuntu-22.04'
    dependsOn:
      - "build_linux_amd64"
    strategy:
      matrix:
        node18_amqp_iothub_module_and_device:              { suite: node18_amqp_iothub_module_and_device }
        node18_amqpws_edgehub_module:           { suite: node18_amqpws_edgehub_module }
        node18_mqttws_edgehub_module:           { suite: node18_mqttws_edgehub_module }
        c_mqtt_iothub_module_and_device:       { suite: c_mqtt_iothub_module_and_device }
        c_mqttws_edgehub_module:              { suite: c_mqttws_edgehub_module }
        java_mqtt_iothub_module:              { suite: java_mqtt_iothub_module }
        csharp_mqtt_iothub_module:            { suite: csharp_mqtt_iothub_module }
        csharp_mqttws_edgehub_module:         { suite: csharp_mqttws_edgehub_module }
        py312_mqtt_iothub_module_and_device_async:    { suite: py312_mqtt_iothub_module_and_device_async }
        py312_mqtt_iothub_module_and_device:          { suite: py312_mqtt_iothub_module_and_device }
        py312_mqtt_edgehub_module_async:              { suite: py312_mqtt_edgehub_module_async }
        py312_mqtt_edgehub_module:                    { suite: py312_mqtt_edgehub_module }
        py312_mqtt_iothub_module_quick_drop:          { suite: py312_mqtt_iothub_device_quick_drop }
    steps:
    - template: templates/steps-load-test-config.yaml
    - template: templates/steps-deploy-and-run-pytest.yaml
      parameters:
        suite: $(suite)

- stage: cleanup
  dependsOn:
  - setup
  - build_and_test
  condition: always()
  jobs:
  - job: destroy_azure_resource_group
    condition: always()
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
    - template: templates/steps-destroy-azure-resources.yaml

