name: $(BuildID)_pythonv2_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
  Horton.Pool: 'Azure Pipelines'
  Horton.VmImage: 'Ubuntu 16.04'

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    variant: py27
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py34
    variant: py34
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py35
    variant: py35
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    variant: py36
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py37
    variant: py37
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py38
    variant: py38
    

- job: "test"
  pool:
    name: $(Horton.Pool)
    vmimage: $(Horton.VmImage)
  dependsOn:
    - "build_py27_container"
    - "build_py34_container"
    - "build_py35_container"
    - "build_py36_container"
    - "build_py37_container"
    - "build_py38_container"
  strategy:
    maxParallel: 20
    matrix:

      py27_mqtt_iothub_module_and_device:           { suite: py27_mqtt_iothub_module_and_device }
      py27_mqtt_edgehub_module:                     { suite: py27_mqtt_edgehub_module }
      py27_mqtt_iothub_module_full_drop:            { suite: py27_mqtt_iothub_module_full_drop }
      py27_mqtt_iothub_device_full_drop:            { suite: py27_mqtt_iothub_device_full_drop }
      py27_mqtt_edgehub_module_full_drop:           { suite: py27_mqtt_edgehub_module_full_drop }

      py27_mqttws_iothub_module_and_device:         { suite: py27_mqttws_iothub_module_and_device }
      py27_mqttws_edgehub_module:                   { suite: py27_mqttws_edgehub_module }
      py27_mqttws_iothub_module_full_drop:          { suite: py27_mqttws_iothub_module_full_drop }
      py27_mqttws_iothub_device_full_drop:          { suite: py27_mqttws_iothub_device_full_drop }
      py27_mqttws_edgehub_module_full_drop:         { suite: py27_mqttws_edgehub_module_full_drop }

      py34_mqtt_iothub_module_and_device:           { suite: py34_mqtt_iothub_module_and_device }
      py34_mqtt_edgehub_module:                     { suite: py34_mqtt_edgehub_module }
      py34_mqtt_iothub_module_full_drop:            { suite: py34_mqtt_iothub_module_full_drop }
      py34_mqtt_iothub_device_full_drop:            { suite: py34_mqtt_iothub_device_full_drop }
      py34_mqtt_edgehub_module_full_drop:           { suite: py34_mqtt_edgehub_module_full_drop }

      py34_mqttws_iothub_module_and_device:         { suite: py34_mqttws_iothub_module_and_device }
      py34_mqttws_edgehub_module:                   { suite: py34_mqttws_edgehub_module }
      py34_mqttws_iothub_module_full_drop:          { suite: py34_mqttws_iothub_module_full_drop }
      py34_mqttws_iothub_device_full_drop:          { suite: py34_mqttws_iothub_device_full_drop }
      py34_mqttws_edgehub_module_full_drop:         { suite: py34_mqttws_edgehub_module_full_drop }

      py35_mqtt_iothub_module_and_device:           { suite: py35_mqtt_iothub_module_and_device }
      py35_mqtt_edgehub_module:                     { suite: py35_mqtt_edgehub_module }
      py35_mqtt_iothub_module_full_drop:            { suite: py35_mqtt_iothub_module_full_drop }
      py35_mqtt_iothub_device_full_drop:            { suite: py35_mqtt_iothub_device_full_drop }
      py35_mqtt_edgehub_module_full_drop:           { suite: py35_mqtt_edgehub_module_full_drop }

      py35_mqttws_iothub_module_and_device:         { suite: py35_mqttws_iothub_module_and_device }
      py35_mqttws_edgehub_module:                   { suite: py35_mqttws_edgehub_module }
      py35_mqttws_iothub_module_full_drop:          { suite: py35_mqttws_iothub_module_full_drop }
      py35_mqttws_iothub_device_full_drop:          { suite: py35_mqttws_iothub_device_full_drop }
      py35_mqttws_edgehub_module_full_drop:         { suite: py35_mqttws_edgehub_module_full_drop }

      py35_async_mqtt_iothub_module_and_device:     { suite: py35_async_mqtt_iothub_module_and_device }
      py35_async_mqtt_edgehub_module:               { suite: py35_async_mqtt_edgehub_module }
      py35_async_mqtt_iothub_module_full_drop:      { suite: py35_async_mqtt_iothub_module_full_drop }
      py35_async_mqtt_iothub_device_full_drop:      { suite: py35_async_mqtt_iothub_device_full_drop }
      py35_async_mqtt_edgehub_module_full_drop:     { suite: py35_async_mqtt_edgehub_module_full_drop }

      py35_async_mqttws_iothub_module_and_device:   { suite: py35_async_mqttws_iothub_module_and_device }
      py35_async_mqttws_edgehub_module:             { suite: py35_async_mqttws_edgehub_module }
      py35_async_mqttws_iothub_module_full_drop:    { suite: py35_async_mqttws_iothub_module_full_drop }
      py35_async_mqttws_iothub_device_full_drop:    { suite: py35_async_mqttws_iothub_device_full_drop }
      py35_async_mqttws_edgehub_module_full_drop:   { suite: py35_async_mqttws_edgehub_module_full_drop }

      py36_mqtt_iothub_module_and_device:           { suite: py36_mqtt_iothub_module_and_device }
      py36_mqtt_edgehub_module:                     { suite: py36_mqtt_edgehub_module }
      py36_mqtt_iothub_module_full_drop:            { suite: py36_mqtt_iothub_module_full_drop }
      py36_mqtt_iothub_device_full_drop:            { suite: py36_mqtt_iothub_device_full_drop }
      py36_mqtt_edgehub_module_full_drop:           { suite: py36_mqtt_edgehub_module_full_drop }

      py36_mqttws_iothub_module_and_device:         { suite: py36_mqttws_iothub_module_and_device }
      py36_mqttws_edgehub_module:                   { suite: py36_mqttws_edgehub_module }
      py36_mqttws_iothub_module_full_drop:          { suite: py36_mqttws_iothub_module_full_drop }
      py36_mqttws_iothub_device_full_drop:          { suite: py36_mqttws_iothub_device_full_drop }
      py36_mqttws_edgehub_module_full_drop:         { suite: py36_mqttws_edgehub_module_full_drop }

      py36_async_mqtt_iothub_module_and_device:     { suite: py36_async_mqtt_iothub_module_and_device }
      py36_async_mqtt_edgehub_module:               { suite: py36_async_mqtt_edgehub_module }
      py36_async_mqtt_iothub_module_full_drop:      { suite: py36_async_mqtt_iothub_module_full_drop }
      py36_async_mqtt_iothub_device_full_drop:      { suite: py36_async_mqtt_iothub_device_full_drop }
      py36_async_mqtt_edgehub_module_full_drop:     { suite: py36_async_mqtt_edgehub_module_full_drop }

      py36_async_mqttws_iothub_module_and_device:   { suite: py36_async_mqttws_iothub_module_and_device }
      py36_async_mqttws_edgehub_module:             { suite: py36_async_mqttws_edgehub_module }
      py36_async_mqttws_iothub_module_full_drop:    { suite: py36_async_mqttws_iothub_module_full_drop }
      py36_async_mqttws_iothub_device_full_drop:    { suite: py36_async_mqttws_iothub_device_full_drop }
      py36_async_mqttws_edgehub_module_full_drop:   { suite: py36_async_mqttws_edgehub_module_full_drop }

      py37_mqtt_iothub_module_and_device:           { suite: py37_mqtt_iothub_module_and_device }
      py37_mqtt_edgehub_module:                     { suite: py37_mqtt_edgehub_module }
      py37_mqtt_iothub_module_full_drop:            { suite: py37_mqtt_iothub_module_full_drop }
      py37_mqtt_iothub_device_full_drop:            { suite: py37_mqtt_iothub_device_full_drop }
      py37_mqtt_edgehub_module_full_drop:           { suite: py37_mqtt_edgehub_module_full_drop }

      py37_mqttws_iothub_module_and_device:         { suite: py37_mqttws_iothub_module_and_device }
      py37_mqttws_edgehub_module:                   { suite: py37_mqttws_edgehub_module }
      py37_mqttws_iothub_module_full_drop:          { suite: py37_mqttws_iothub_module_full_drop }
      py37_mqttws_iothub_device_full_drop:          { suite: py37_mqttws_iothub_device_full_drop }
      py37_mqttws_edgehub_module_full_drop:         { suite: py37_mqttws_edgehub_module_full_drop }

      py37_async_mqtt_iothub_module_and_device:     { suite: py37_async_mqtt_iothub_module_and_device }
      py37_async_mqtt_edgehub_module:               { suite: py37_async_mqtt_edgehub_module }
      py37_async_mqtt_iothub_module_full_drop:      { suite: py37_async_mqtt_iothub_module_full_drop }
      py37_async_mqtt_iothub_device_full_drop:      { suite: py37_async_mqtt_iothub_device_full_drop }
      py37_async_mqtt_edgehub_module_full_drop:     { suite: py37_async_mqtt_edgehub_module_full_drop }

      py37_async_mqttws_iothub_module_and_device:   { suite: py37_async_mqttws_iothub_module_and_device }
      py37_async_mqttws_edgehub_module:             { suite: py37_async_mqttws_edgehub_module }
      py37_async_mqttws_iothub_module_full_drop:    { suite: py37_async_mqttws_iothub_module_full_drop }
      py37_async_mqttws_iothub_device_full_drop:    { suite: py37_async_mqttws_iothub_device_full_drop }
      py37_async_mqttws_edgehub_module_full_drop:   { suite: py37_async_mqttws_edgehub_module_full_drop }

      py38_mqtt_iothub_module_and_device:           { suite: py38_mqtt_iothub_module_and_device }
      py38_mqtt_edgehub_module:                     { suite: py38_mqtt_edgehub_module }
      py38_mqtt_iothub_module_full_drop:            { suite: py38_mqtt_iothub_module_full_drop }
      py38_mqtt_iothub_device_full_drop:            { suite: py38_mqtt_iothub_device_full_drop }
      py38_mqtt_edgehub_module_full_drop:           { suite: py38_mqtt_edgehub_module_full_drop }

      py38_mqttws_iothub_module_and_device:         { suite: py38_mqttws_iothub_module_and_device }
      py38_mqttws_edgehub_module:                   { suite: py38_mqttws_edgehub_module }
      py38_mqttws_iothub_module_full_drop:          { suite: py38_mqttws_iothub_module_full_drop }
      py38_mqttws_iothub_device_full_drop:          { suite: py38_mqttws_iothub_device_full_drop }
      py38_mqttws_edgehub_module_full_drop:         { suite: py38_mqttws_edgehub_module_full_drop }

      py38_async_mqtt_iothub_module_and_device:     { suite: py38_async_mqtt_iothub_module_and_device }
      py38_async_mqtt_edgehub_module:               { suite: py38_async_mqtt_edgehub_module }
      py38_async_mqtt_iothub_module_full_drop:      { suite: py38_async_mqtt_iothub_module_full_drop }
      py38_async_mqtt_iothub_device_full_drop:      { suite: py38_async_mqtt_iothub_device_full_drop }
      py38_async_mqtt_edgehub_module_full_drop:     { suite: py38_async_mqtt_edgehub_module_full_drop }

      py38_async_mqttws_iothub_module_and_device:   { suite: py38_async_mqttws_iothub_module_and_device }
      py38_async_mqttws_edgehub_module:             { suite: py38_async_mqttws_edgehub_module }
      py38_async_mqttws_iothub_module_full_drop:    { suite: py38_async_mqttws_iothub_module_full_drop }
      py38_async_mqttws_iothub_device_full_drop:    { suite: py38_async_mqttws_iothub_device_full_drop }
      py38_async_mqttws_edgehub_module_full_drop:   { suite: py38_async_mqttws_edgehub_module_full_drop }


  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

