name: $(BuildID)_java_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: java
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      java_mqtt_iothub_module:      { suite: java_mqtt_iothub_module }
      java_mqtt_edgehub_module:     { suite: java_mqtt_edgehub_module }
      java_mqttws_iothub_module:    { suite: java_mqttws_iothub_module }
      java_mqttws_edgehub_module:   { suite: java_mqttws_edgehub_module }
      java_amqp_iothub_module:      { suite: java_amqp_iothub_module }
      java_amqp_edgehub_module:     { suite: java_amqp_edgehub_module }
      java_amqpws_iothub_module:    { suite: java_amqpws_iothub_module }
      java_amqpws_edgehub_module:   { suite: java_amqpws_edgehub_module }
  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

