name: $(BuildID)_c_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_container"
  strategy:
    matrix:
      c_mqtt_iothub_module:     { suite: c_mqtt_iothub_module }
      c_mqtt_edgehub_module:    { suite: c_mqtt_edgehub_module }
      c_mqttws_iothub_module:   { suite: c_mqttws_iothub_module }
      c_mqttws_edgehub_module:  { suite: c_mqttws_edgehub_module }
      c_amqp_iothub_module:     { suite: c_amqp_iothub_module }
      c_amqp_edgehub_module:    { suite: c_amqp_edgehub_module }
      c_amqpws_iothub_module:   { suite: c_amqpws_iothub_module }
      c_amqpws_edgehub_module:  { suite: c_amqpws_edgehub_module }
  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

