name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    variant: py27
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py34
    variant: py34
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py35
    variant: py35
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    variant: py36
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py37
    variant: py37

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_py27_container"
    - "build_py34_container"
    - "build_py35_container"
    - "build_py36_container"
    - "build_py37_container"
  strategy:
    maxParallel: 15
    matrix:
      edgehub_module_mqtt_27:
        suite: edgehub_module_mqtt
        variant: py27
        async: no
      edgehub_module_mqtt_ws_27:
        suite: edgehub_module_mqtt_ws
        variant: py27
        async: no
      iothub_module_and_device_mqtt_27:
        suite: iothub_module_and_device_mqtt
        variant: py27
        async: no
      iothub_module_and_device_mqtt_ws_27:
        suite: iothub_module_and_device_mqtt_ws
        variant: py27
        async: no
      edgehub_module_mqtt_34:
        suite: edgehub_module_mqtt
        variant: py34
      edgehub_module_mqtt_ws_34:
        suite: edgehub_module_mqtt_ws
        variant: py34
        async: no
      iothub_module_and_device_mqtt_34:
        suite: iothub_module_and_device_mqtt
        variant: py34
        async: no
      iothub_module_and_device_mqtt_ws_34:
        suite: iothub_module_and_device_mqtt_ws
        variant: py34
        async: no
      edgehub_module_mqtt_35:
        suite: edgehub_module_mqtt
        variant: py35
        async: no
      edgehub_module_mqtt_ws_35:
        suite: edgehub_module_mqtt_ws
        variant: py35
        async: no
      iothub_module_and_device_mqtt_35:
        suite: iothub_module_and_device_mqtt
        variant: py35
        async: no
      iothub_module_and_device_mqtt_ws_35:
        suite: iothub_module_and_device_mqtt_ws
        variant: py35
        async: no
      edgehub_module_mqtt_36:
        suite: edgehub_module_mqtt
        variant: py36
        async: no
      edgehub_module_mqtt_ws_36:
        suite: edgehub_module_mqtt_ws
        variant: py36
        async: no
      iothub_module_and_device_mqtt_36:
        suite: iothub_module_and_device_mqtt
        variant: py36
        async: no
      iothub_module_and_device_mqtt_ws_36:
        suite: iothub_module_and_device_mqtt_ws
        variant: py36
        async: no
      edgehub_module_mqtt_37:
        suite: edgehub_module_mqtt
        variant: py37
        async: no
      edgehub_module_mqtt_ws_37:
        suite: edgehub_module_mqtt_ws
        variant: py37
        async: no
      iothub_module_and_device_mqtt_37:
        suite: iothub_module_and_device_mqtt
        variant: py37
        async: no
      iothub_module_and_device_mqtt_ws_37:
        suite: iothub_module_and_device_mqtt_ws
        variant: py37
        async: no
      iothub_module_and_device_mqtt_35_async:
        suite: iothub_module_and_device_mqtt
        variant: py35
        async: yes
      iothub_module_and_device_mqtt_ws_35_async:
        suite: iothub_module_and_device_mqtt_ws
        variant: py35
        async: yes
      iothub_module_and_device_mqtt_36_async:
        suite: iothub_module_and_device_mqtt
        variant: py36
        async: yes
      iothub_module_and_device_mqtt_ws_36_async:
        suite: iothub_module_and_device_mqtt_ws
        variant: py36
        async: yes
      iothub_module_and_device_mqtt_37_async:
        suite: iothub_module_and_device_mqtt
        variant: py37
        async: yes
      iothub_module_and_device_mqtt_ws_37_async:
        suite: iothub_module_and_device_mqtt_ws
        variant: py37
        async: yes
      edgehub_module_mqtt_35_async:
        suite: edgehub_module_mqtt
        variant: py35
        async: yes
      edgehub_module_mqtt_ws_35_async:
        suite: edgehub_module_mqtt_ws
        variant: py35
        async: yes
      edgehub_module_mqtt_36_async:
        suite: edgehub_module_mqtt
        variant: py36
        async: yes
      edgehub_module_mqtt_ws_36_async:
        suite: edgehub_module_mqtt_ws
        variant: py36
        async: yes
      edgehub_module_mqtt_37_async:
        suite: edgehub_module_mqtt
        variant: py37
        async: yes
      edgehub_module_mqtt_ws_37_async:
        suite: edgehub_module_mqtt_ws
        variant: py37
        async: yes

  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)
      variant: $(variant)
      async: $(async)

