name: $(BuildID)_pythonv2_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py27
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py34
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py35
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py36
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py37
    
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: pythonv2
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)
    job_tag: py38
    

- job: "test"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_py27_container"
    - "build_py34_container"
    - "build_py35_container"
    - "build_py36_container"
    - "build_py37_container"
    - "build_py38_container"
  strategy:
    maxParallel: 10
    matrix:
      py27_mqtt_iothub_module_and_device:           { suite: py27_mqtt_iothub_module_and_device }
      py27_mqtt_edgehub_module:                     { suite: py27_mqtt_edgehub_module }
      py27_mqttws_iothub_module_and_device:         { suite: py27_mqttws_iothub_module_and_device }
      py27_mqttws_edgehub_module:                   { suite: py27_mqttws_edgehub_module }

      py35_mqtt_iothub_module_and_device:           { suite: py35_mqtt_iothub_module_and_device }
      py35_mqtt_edgehub_module:                     { suite: py35_mqtt_edgehub_module }
      py35_mqttws_iothub_module_and_device:         { suite: py35_mqttws_iothub_module_and_device }
      py35_mqttws_edgehub_module:                   { suite: py35_mqttws_edgehub_module }

      py35_mqtt_async_iothub_module_and_device:     { suite: py35_mqtt_async_iothub_module_and_device }
      py35_mqtt_async_edgehub_module:               { suite: py35_mqtt_async_edgehub_module }
      py35_mqttws_async_iothub_module_and_device:   { suite: py35_mqttws_async_iothub_module_and_device }
      py35_mqttws_async__edgehub_module:            { suite: py35_mqttws_async__edgehub_module }

      py36_mqtt_iothub_module_and_device:           { suite: py36_mqtt_iothub_module_and_device }
      py36_mqtt_edgehub_module:                     { suite: py36_mqtt_edgehub_module }
      py36_mqttws_iothub_module_and_device:         { suite: py36_mqttws_iothub_module_and_device }
      py36_mqttws_edgehub_module:                   { suite: py36_mqttws_edgehub_module }

      py36_mqtt_async_iothub_module_and_device:     { suite: py36_mqtt_async_iothub_module_and_device }
      py36_mqtt_async_edgehub_module:               { suite: py36_mqtt_async_edgehub_module }
      py36_mqttws_async_iothub_module_and_device:   { suite: py36_mqttws_async_iothub_module_and_device }
      py36_mqttws_async_edgehub_module:             { suite: py36_mqttws_async_edgehub_module }

      py37_mqtt_iothub_module_and_device:           { suite: py37_mqtt_iothub_module_and_device }
      py37_mqtt_edgehub_module:                     { suite: py37_mqtt_edgehub_module }
      py37_mqttws_iothub_module_and_device:         { suite: py37_mqttws_iothub_module_and_device }
      py37_mqttws_edgehub_module:                   { suite: py37_mqttws_edgehub_module }

      py37_mqtt_async_iothub_module_and_device:     { suite: py37_mqtt_async_iothub_module_and_device }
      py37_mqtt_async_edgehub_module:               { suite: py37_mqtt_async_edgehub_module }
      py37_mqttws_async_iothub_module_and_device:   { suite: py37_mqttws_async_iothub_module_and_device }
      py37_mqttws_async_edgehub_module:             { suite: py37_mqttws_async_edgehub_module }

      py38_mqtt_iothub_module_and_device:           { suite: py38_mqtt_iothub_module_and_device }
      py38_mqtt_edgehub_module:                     { suite: py38_mqtt_edgehub_module }
      py38_mqttws_iothub_module_and_device:         { suite: py38_mqttws_iothub_module_and_device }
      py38_mqttws_edgehub_module:                   { suite: py38_mqttws_edgehub_module }

      py38_mqtt_async_iothub_module_and_device:     { suite: py38_mqtt_async_iothub_module_and_device }
      py38_mqtt_async_edgehub_module:               { suite: py38_mqtt_async_edgehub_module }
      py38_mqttws_async_iothub_module_and_device:   { suite: py38_mqttws_async_iothub_module_and_device }
      py38_mqttws_async_edgehub_module:             { suite: py38_mqttws_async_edgehub_module }

  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

