name: $(BuildID)_pythonv2_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- job: "build_linux_amd64"
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      py38: { variant: py38 }
      py37: { variant: py37 }
      py36: { variant: py36 }
      py35: { variant: py35 }
      py27: { variant: py27 }
  steps:
  - template: templates/steps-build-docker-image.yaml
    parameters:
      variant: $(variant)

- job: "test_linux_amd64"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_linux_amd64"
  strategy:
    maxParallel: 20
    matrix:

      py27_mqtt_iothub_module_and_device:           { suite: py27_mqtt_iothub_module_and_device }
      py27_mqtt_edgehub_module:                     { suite: py27_mqtt_edgehub_module }
      py27_mqtt_iothub_module_full_drop:            { suite: py27_mqtt_iothub_module_full_drop }
      py27_mqtt_iothub_device_full_drop:            { suite: py27_mqtt_iothub_device_full_drop }
      py27_mqtt_edgehub_module_full_drop:           { suite: py27_mqtt_edgehub_module_full_drop }

      py27_mqttws_iothub_module_and_device:         { suite: py27_mqttws_iothub_module_and_device }
      py27_mqttws_edgehub_module:                   { suite: py27_mqttws_edgehub_module }
      py27_mqttws_iothub_module_full_drop:          { suite: py27_mqttws_iothub_module_full_drop }
      py27_mqttws_iothub_device_full_drop:          { suite: py27_mqttws_iothub_device_full_drop }
      py27_mqttws_edgehub_module_full_drop:         { suite: py27_mqttws_edgehub_module_full_drop }

      py35_mqtt_iothub_module_and_device:           { suite: py35_mqtt_iothub_module_and_device }
      py35_mqtt_edgehub_module:                     { suite: py35_mqtt_edgehub_module }
      py35_mqtt_iothub_module_full_drop:            { suite: py35_mqtt_iothub_module_full_drop }
      py35_mqtt_iothub_device_full_drop:            { suite: py35_mqtt_iothub_device_full_drop }
      py35_mqtt_edgehub_module_full_drop:           { suite: py35_mqtt_edgehub_module_full_drop }

      py35_mqttws_iothub_module_and_device:         { suite: py35_mqttws_iothub_module_and_device }
      py35_mqttws_edgehub_module:                   { suite: py35_mqttws_edgehub_module }
      py35_mqttws_iothub_module_full_drop:          { suite: py35_mqttws_iothub_module_full_drop }
      py35_mqttws_iothub_device_full_drop:          { suite: py35_mqttws_iothub_device_full_drop }
      py35_mqttws_edgehub_module_full_drop:         { suite: py35_mqttws_edgehub_module_full_drop }

      py35_async_mqtt_iothub_module_and_device:     { suite: py35_async_mqtt_iothub_module_and_device }
      py35_async_mqtt_edgehub_module:               { suite: py35_async_mqtt_edgehub_module }
      py35_async_mqtt_iothub_module_full_drop:      { suite: py35_async_mqtt_iothub_module_full_drop }
      py35_async_mqtt_iothub_device_full_drop:      { suite: py35_async_mqtt_iothub_device_full_drop }
      py35_async_mqtt_edgehub_module_full_drop:     { suite: py35_async_mqtt_edgehub_module_full_drop }

      py35_async_mqttws_iothub_module_and_device:   { suite: py35_async_mqttws_iothub_module_and_device }
      py35_async_mqttws_edgehub_module:             { suite: py35_async_mqttws_edgehub_module }
      py35_async_mqttws_iothub_module_full_drop:    { suite: py35_async_mqttws_iothub_module_full_drop }
      py35_async_mqttws_iothub_device_full_drop:    { suite: py35_async_mqttws_iothub_device_full_drop }
      py35_async_mqttws_edgehub_module_full_drop:   { suite: py35_async_mqttws_edgehub_module_full_drop }

      py36_mqtt_iothub_module_and_device:           { suite: py36_mqtt_iothub_module_and_device }
      py36_mqtt_edgehub_module:                     { suite: py36_mqtt_edgehub_module }
      py36_mqtt_iothub_module_full_drop:            { suite: py36_mqtt_iothub_module_full_drop }
      py36_mqtt_iothub_device_full_drop:            { suite: py36_mqtt_iothub_device_full_drop }
      py36_mqtt_edgehub_module_full_drop:           { suite: py36_mqtt_edgehub_module_full_drop }

      py36_mqttws_iothub_module_and_device:         { suite: py36_mqttws_iothub_module_and_device }
      py36_mqttws_edgehub_module:                   { suite: py36_mqttws_edgehub_module }
      py36_mqttws_iothub_module_full_drop:          { suite: py36_mqttws_iothub_module_full_drop }
      py36_mqttws_iothub_device_full_drop:          { suite: py36_mqttws_iothub_device_full_drop }
      py36_mqttws_edgehub_module_full_drop:         { suite: py36_mqttws_edgehub_module_full_drop }

      py36_async_mqtt_iothub_module_and_device:     { suite: py36_async_mqtt_iothub_module_and_device }
      py36_async_mqtt_edgehub_module:               { suite: py36_async_mqtt_edgehub_module }
      py36_async_mqtt_iothub_module_full_drop:      { suite: py36_async_mqtt_iothub_module_full_drop }
      py36_async_mqtt_iothub_device_full_drop:      { suite: py36_async_mqtt_iothub_device_full_drop }
      py36_async_mqtt_edgehub_module_full_drop:     { suite: py36_async_mqtt_edgehub_module_full_drop }

      py36_async_mqttws_iothub_module_and_device:   { suite: py36_async_mqttws_iothub_module_and_device }
      py36_async_mqttws_edgehub_module:             { suite: py36_async_mqttws_edgehub_module }
      py36_async_mqttws_iothub_module_full_drop:    { suite: py36_async_mqttws_iothub_module_full_drop }
      py36_async_mqttws_iothub_device_full_drop:    { suite: py36_async_mqttws_iothub_device_full_drop }
      py36_async_mqttws_edgehub_module_full_drop:   { suite: py36_async_mqttws_edgehub_module_full_drop }

      py37_mqtt_iothub_module_and_device:           { suite: py37_mqtt_iothub_module_and_device }
      py37_mqtt_edgehub_module:                     { suite: py37_mqtt_edgehub_module }
      py37_mqtt_iothub_module_full_drop:            { suite: py37_mqtt_iothub_module_full_drop }
      py37_mqtt_iothub_device_full_drop:            { suite: py37_mqtt_iothub_device_full_drop }
      py37_mqtt_edgehub_module_full_drop:           { suite: py37_mqtt_edgehub_module_full_drop }

      py37_mqttws_iothub_module_and_device:         { suite: py37_mqttws_iothub_module_and_device }
      py37_mqttws_edgehub_module:                   { suite: py37_mqttws_edgehub_module }
      py37_mqttws_iothub_module_full_drop:          { suite: py37_mqttws_iothub_module_full_drop }
      py37_mqttws_iothub_device_full_drop:          { suite: py37_mqttws_iothub_device_full_drop }
      py37_mqttws_edgehub_module_full_drop:         { suite: py37_mqttws_edgehub_module_full_drop }

      py37_async_mqtt_iothub_module_and_device:     { suite: py37_async_mqtt_iothub_module_and_device }
      py37_async_mqtt_edgehub_module:               { suite: py37_async_mqtt_edgehub_module }
      py37_async_mqtt_iothub_module_full_drop:      { suite: py37_async_mqtt_iothub_module_full_drop }
      py37_async_mqtt_iothub_device_full_drop:      { suite: py37_async_mqtt_iothub_device_full_drop }
      py37_async_mqtt_edgehub_module_full_drop:     { suite: py37_async_mqtt_edgehub_module_full_drop }

      py37_async_mqttws_iothub_module_and_device:   { suite: py37_async_mqttws_iothub_module_and_device }
      py37_async_mqttws_edgehub_module:             { suite: py37_async_mqttws_edgehub_module }
      py37_async_mqttws_iothub_module_full_drop:    { suite: py37_async_mqttws_iothub_module_full_drop }
      py37_async_mqttws_iothub_device_full_drop:    { suite: py37_async_mqttws_iothub_device_full_drop }
      py37_async_mqttws_edgehub_module_full_drop:   { suite: py37_async_mqttws_edgehub_module_full_drop }

      py38_mqtt_iothub_module_and_device:           { suite: py38_mqtt_iothub_module_and_device }
      py38_mqtt_edgehub_module:                     { suite: py38_mqtt_edgehub_module }
      py38_mqtt_iothub_module_full_drop:            { suite: py38_mqtt_iothub_module_full_drop }
      py38_mqtt_iothub_device_full_drop:            { suite: py38_mqtt_iothub_device_full_drop }
      py38_mqtt_edgehub_module_full_drop:           { suite: py38_mqtt_edgehub_module_full_drop }

      py38_mqttws_iothub_module_and_device:         { suite: py38_mqttws_iothub_module_and_device }
      py38_mqttws_edgehub_module:                   { suite: py38_mqttws_edgehub_module }
      py38_mqttws_iothub_module_full_drop:          { suite: py38_mqttws_iothub_module_full_drop }
      py38_mqttws_iothub_device_full_drop:          { suite: py38_mqttws_iothub_device_full_drop }
      py38_mqttws_edgehub_module_full_drop:         { suite: py38_mqttws_edgehub_module_full_drop }

      py38_async_mqtt_iothub_module_and_device:     { suite: py38_async_mqtt_iothub_module_and_device }
      py38_async_mqtt_edgehub_module:               { suite: py38_async_mqtt_edgehub_module }
      py38_async_mqtt_iothub_module_full_drop:      { suite: py38_async_mqtt_iothub_module_full_drop }
      py38_async_mqtt_iothub_device_full_drop:      { suite: py38_async_mqtt_iothub_device_full_drop }
      py38_async_mqtt_edgehub_module_full_drop:     { suite: py38_async_mqtt_edgehub_module_full_drop }

      py38_async_mqttws_iothub_module_and_device:   { suite: py38_async_mqttws_iothub_module_and_device }
      py38_async_mqttws_edgehub_module:             { suite: py38_async_mqttws_edgehub_module }
      py38_async_mqttws_iothub_module_full_drop:    { suite: py38_async_mqttws_iothub_module_full_drop }
      py38_async_mqttws_iothub_device_full_drop:    { suite: py38_async_mqttws_iothub_device_full_drop }
      py38_async_mqttws_edgehub_module_full_drop:   { suite: py38_async_mqttws_edgehub_module_full_drop }


  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

- job: "tag_lkg_amd64"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
     "test_linux_amd64"
  steps:
  - template: templates/steps-tag-lkg.yaml
    parameters:
      language: pythonv2
