name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: node
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    job_tag: node6
    variant: node6
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: node
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    job_tag: node8
    variant: node8
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: node
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    job_tag: node10
    variant: node10

- job: "test_node6"
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - "build_node6_container"
    - "build_node8_container"
    - "build_node10_container"
  strategy:
    matrix:
      node6_mqtt_iothub_module:     { suite: node6_mqtt_iothub_module }
      node6_mqtt_edgehub_module:    { suite: node6_mqtt_edgehub_module }
      node6_mqttws_iothub_module:   { suite: node6_mqttws_iothub_module }
      node6_mqttws_edgehub_module:  { suite: node6_mqttws_edgehub_module }
      node6_amqp_iothub_module:     { suite: node6_amqp_iothub_module }
      node6_amqp_edgehub_module:    { suite: node6_amqp_edgehub_module }
      node6_amqpws_iothub_module:   { suite: node6_amqpws_iothub_module }
      node6_amqpws_edgehub_module:  { suite: node6_amqpws_edgehub_module }

      node8_mqtt_iothub_module:     { suite: node8_mqtt_iothub_module }
      node8_mqtt_edgehub_module:    { suite: node8_mqtt_edgehub_module }
      node8_mqttws_iothub_module:   { suite: node8_mqttws_iothub_module }
      node8_mqttws_edgehub_module:  { suite: node8_mqttws_edgehub_module }
      node8_amqp_iothub_module:     { suite: node8_amqp_iothub_module }
      node8_amqp_edgehub_module:    { suite: node8_amqp_edgehub_module }
      node8_amqpws_iothub_module:   { suite: node8_amqpws_iothub_module }
      node8_amqpws_edgehub_module:  { suite: node8_amqpws_edgehub_module }

      node10_mqtt_iothub_module:    { suite: node10_mqtt_iothub_module }
      node10_mqtt_edgehub_module:   { suite: node10_mqtt_edgehub_module }
      node10_mqttws_iothub_module:  { suite: node10_mqttws_iothub_module }
      node10_mqttws_edgehub_module: { suite: node10_mqttws_edgehub_module }
      node10_amqp_iothub_module:    { suite: node10_amqp_iothub_module }
      node10_amqp_edgehub_module:   { suite: node10_amqp_edgehub_module }
      node10_amqpws_iothub_module:  { suite: node10_amqpws_iothub_module }
      node10_amqpws_edgehub_module: { suite: node10_amqpws_edgehub_module }
  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)


