name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- job: "build_linux_arm"
  timeoutInMinutes: 120
  pool: "Horton_Tests"
  strategy:
    matrix:
      py37: { variant: py37 }
  steps:
  - template: templates/steps-build-docker-image.yaml
    parameters:
      variant: $(variant)
      language: $(language)

- job: "test_linux_arm"
  pool: "Horton_Tests"
  dependsOn:
    - "build_linux_arm"
  strategy:
    matrix:
      py37_mqtt_iothub_module_and_device:     { suite: py37_mqtt_iothub_module_and_device }
      py37_mqtt_edgehub_module:               { suite: py37_mqtt_edgehub_module }
  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)


