jobs:
- job: 'run_tests'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/pre-test-steps.yaml
    parameters:
      language: $(TARGET_SDK)
      imagetag: $(IMAGE)
  - template: templates/post-test-steps.yaml
