name: $(BuildID)_$(Horton.Language)_$(Horton.Commit)_$(BuildDefinitionName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: 'run_tests'
  pool:
      vmImage: 'Ubuntu 16.04'
  dependsOn:
    - 'build_linux_container'
  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      forced_image: $(Horton.ForcedImage)
      suite: $(Horton.Suite)
      testcase: $(Horton.TestCase)
      repeat_count: $(Horton.RepeatCount)
