variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  dependsOn:
    - "build_linux_container"
  strategy:
    maxParallel: 4
    matrix:
      aa_iothub_module_mqtt: { suite: iothub_module_mqtt }
      aa_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      aa_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      aa_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      aa_iothub_module_amqp: { suite: iothub_module_amqp }
      aa_edgehub_module_amqp: { suite: edgehub_module_amqp }
      aa_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      aa_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      ab_iothub_module_mqtt: { suite: iothub_module_mqtt }
      ab_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      ab_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      ab_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      ab_iothub_module_amqp: { suite: iothub_module_amqp }
      ab_edgehub_module_amqp: { suite: edgehub_module_amqp }
      ab_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ab_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      ac_iothub_module_mqtt: { suite: iothub_module_mqtt }
      ac_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      ac_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      ac_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      ac_iothub_module_amqp: { suite: iothub_module_amqp }
      ac_edgehub_module_amqp: { suite: edgehub_module_amqp }
      ac_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ac_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      ad_iothub_module_mqtt: { suite: iothub_module_mqtt }
      ad_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      ad_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      ad_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      ad_iothub_module_amqp: { suite: iothub_module_amqp }
      ad_edgehub_module_amqp: { suite: edgehub_module_amqp }
      ad_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ad_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      ae_iothub_module_mqtt: { suite: iothub_module_mqtt }
      ae_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      ae_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      ae_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      ae_iothub_module_amqp: { suite: iothub_module_amqp }
      ae_edgehub_module_amqp: { suite: edgehub_module_amqp }
      ae_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ae_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      ba_iothub_module_mqtt: { suite: iothub_module_mqtt }
      ba_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      ba_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      ba_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      ba_iothub_module_amqp: { suite: iothub_module_amqp }
      ba_edgehub_module_amqp: { suite: edgehub_module_amqp }
      ba_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ba_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      bb_iothub_module_mqtt: { suite: iothub_module_mqtt }
      bb_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      bb_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      bb_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      bb_iothub_module_amqp: { suite: iothub_module_amqp }
      bb_edgehub_module_amqp: { suite: edgehub_module_amqp }
      bb_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      bb_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      bc_iothub_module_mqtt: { suite: iothub_module_mqtt }
      bc_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      bc_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      bc_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      bc_iothub_module_amqp: { suite: iothub_module_amqp }
      bc_edgehub_module_amqp: { suite: edgehub_module_amqp }
      bc_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      bc_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      bd_iothub_module_mqtt: { suite: iothub_module_mqtt }
      bd_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      bd_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      bd_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      bd_iothub_module_amqp: { suite: iothub_module_amqp }
      bd_edgehub_module_amqp: { suite: edgehub_module_amqp }
      bd_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      bd_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      be_iothub_module_mqtt: { suite: iothub_module_mqtt }
      be_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      be_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      be_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      be_iothub_module_amqp: { suite: iothub_module_amqp }
      be_edgehub_module_amqp: { suite: edgehub_module_amqp }
      be_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      ee_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
    docker restart edgeHub ${{ parameters.language }}Mod

  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

