name: $(BuildID)_$(Horton.Language)_$(Horton.Commit)_$(BuildDefinitionName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

jobs:
- template: templates/jobs-build-docker-image.yaml
  parameters:
    language: $(Horton.Language)
    repo: $(Horton.Repo)
    commit: $(Horton.Commit)
    forced_image: $(Horton.ForcedImage)

- job: "test"
  dependsOn:
    - "build_linux_container"
  strategy:
    maxParallel: 4
    matrix:
      a1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      a2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      a3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      a4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      a5_iothub_module_amqp: { suite: iothub_module_amqp }
      a6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      a7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      a8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      b1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      b2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      b3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      b4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      b5_iothub_module_amqp: { suite: iothub_module_amqp }
      b6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      b7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      b8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      c1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      c2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      c3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      c4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      c5_iothub_module_amqp: { suite: iothub_module_amqp }
      c6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      c7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      c8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      d1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      d2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      d3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      d4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      d5_iothub_module_amqp: { suite: iothub_module_amqp }
      d6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      d7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      d8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      e1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      e2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      e3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      e4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      e5_iothub_module_amqp: { suite: iothub_module_amqp }
      e6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      e7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      e8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      f1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      f2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      f3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      f4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      f5_iothub_module_amqp: { suite: iothub_module_amqp }
      f6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      f7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      f8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      g1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      g2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      g3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      g4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      g5_iothub_module_amqp: { suite: iothub_module_amqp }
      g6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      g7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      g8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      h1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      h2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      h3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      h4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      h5_iothub_module_amqp: { suite: iothub_module_amqp }
      h6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      h7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      h8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      i1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      i2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      i3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      i4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      i5_iothub_module_amqp: { suite: iothub_module_amqp }
      i6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      i7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      i8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }
      j1_iothub_module_mqtt: { suite: iothub_module_mqtt }
      j2_edgehub_module_mqtt: { suite: edgehub_module_mqtt }
      j3_iothub_module_mqtt_ws: { suite: iothub_module_mqtt_ws }
      j4_edgehub_module_mqtt_ws: { suite: edgehub_module_mqtt_ws }
      j5_iothub_module_amqp: { suite: iothub_module_amqp }
      j6_edgehub_module_amqp: { suite: edgehub_module_amqp }
      j7_iothub_module_amqp_ws: { suite: iothub_module_amqp_ws }
      j8_edgehub_module_amqp_ws: { suite: edgehub_module_amqp_ws }

  steps:
  - template: templates/steps-deploy-and-run-pytest.yaml
    parameters:
      language: $(Horton.Language)
      forced_image: $(Horton.ForcedImage)
      suite: $(suite)

