# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Certificate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cert=None):  # noqa: E501
        """Certificate - a model defined in Swagger

        :param cert: The cert of this Certificate.  # noqa: E501
        :type cert: str
        """
        self.swagger_types = {
            'cert': str
        }

        self.attribute_map = {
            'cert': 'cert'
        }

        self._cert = cert

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The certificate of this Certificate.  # noqa: E501
        :rtype: Certificate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cert(self):
        """Gets the cert of this Certificate.

        unique identifier for this connection  # noqa: E501

        :return: The cert of this Certificate.
        :rtype: str
        """
        return self._cert

    @cert.setter
    def cert(self, cert):
        """Sets the cert of this Certificate.

        unique identifier for this connection  # noqa: E501

        :param cert: The cert of this Certificate.
        :type cert: str
        """

        self._cert = cert
